name: qycli-php81
base: core20
adopt-info: qycli-php81
summary: PHP 8.1 for the qycli LEMP stack - qycli.org
description: |
  Compiled PHP binaries carrier for the qycli LEMP stack.
  This product includes PHP software, freely available from http://www.php.net/software/

grade: stable
confinement: strict

architectures:
  - build-on: amd64

parts:
  qycli-php81:
    plugin: autotools
    override-pull: |
      php_major_version=8.1
      php_version=$(curl -s https://www.php.net/downloads.php | tac | tac | grep "<h3 id=\"v$php_major_version.*" | grep -o -P '(?<="v).*(?=" class)')

      snapcraftctl set-version "${php_version}"

      # Downloading supported PHP versions
      wget -qO php.tar.xz https://www.php.net/distributions/php-${php_version}.tar.xz

      # Unpacking the PHP version
      mkdir $SNAPCRAFT_PROJECT_DIR/php
      tar -xf php.tar.xz --strip-components=1 -C $SNAPCRAFT_PROJECT_DIR/php/

      # Downloading external extensions
      declare -a extensions=("imagick" "redis")
      for ext in "${extensions[@]}"
      do
        wget -qO $ext.tgz https://pecl.php.net/get/$ext
        mkdir $SNAPCRAFT_PROJECT_DIR/php/ext/$ext
        tar -zxf $ext.tgz --strip-components=1 -C $SNAPCRAFT_PROJECT_DIR/php/ext/$ext/
      done

      # Deleting configure script for extensions to be compiled also
      cd $SNAPCRAFT_PROJECT_DIR/php/
      rm configure
      ./buildconf --force

      snapcraftctl pull

    source: $SNAPCRAFT_PROJECT_DIR/php/
    source-type: local
    override-build: |
      snapcraftctl build
      cp -rf /php/ $SNAPCRAFT_PART_INSTALL/
    build-packages:
      - software-properties-common
      - curl
      - wget
      - tar
      - php-pear
      - libxml2-dev
      - pkg-config
      - libssl-dev
      - libcurl4-openssl-dev
      - libpng-dev
      - libjpeg8-dev
      - libwebp-dev
      - libmagickwand-dev
      - libzip-dev
      - libargon2-0-dev
      - libonig-dev
      - libsodium-dev
    autotools-configure-parameters:
      - --prefix=/php/
      - --enable-fpm
      - --disable-cgi
      - --disable-phpdbg
      - --enable-sockets
      - --without-sqlite3
      - --without-pdo-sqlite
      - --with-mysqli
      - --with-curl
      - --enable-exif
      - --enable-mbstring
      - --with-openssl
      - --with-zip
      - --enable-bcmath
      - --with-jpeg
      - --with-webp
      - --enable-intl
      - --with-sodium
      - --with-zlib
      - --enable-soap
      - --enable-gd=shared
      - --with-imagick=shared
      - --enable-redis=shared
